### ISSUE TITLE
Not copying to clipboard

### ISSUE THREAD

**Issue by joseparreiras** [GimmyHchs/alfred-workflow-bitly#8]
I try to use the workflow and it is seen on my bit.ly account that the URL was shortened, but it fails to copy it to my clipboard.

**Comment by GimmyHchs** [comment]
> it is seen on my bit.ly account that the URL was shortened 

it means BITLY_ACCESS_TOKEN is correct.

> but it fails to copy it to my clipboard. 

I `guess` that 
- you didn't install jq?
- you set the jq path incorrectly?

Maybe you can check the [installation document](https://github.com/GimmyHchs/alfred-workflow-bitly#installation) first.

---

Get the JQPATH via `which` command.
```
$ which jq
```

example output
```
/usr/local/bin/jq
```

if jq is in a `non-standard location` , set JQPATH. For example: `/usr/lib/bin`

**Comment by GimmyHchs** [comment]
@joseparreiras any update?
